# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ordinalize}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bigg"]
  s.date = %q{2009-12-26}
  s.description = %q{Generates long winded string versions of numbers, ordinalized}
  s.email = %q{radarlistener@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/ordinalize.rb",
     "ordinalize.gemspec",
     "spec/ordinalize_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/radar/ordinalize}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generates long winded string versions of numbers, ordinalized}
  s.test_files = [
    "spec/ordinalize_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<humanize>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<humanize>, [">= 0"])
    end
  else
    s.add_dependency(%q<humanize>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
